# Generated by Django 5.0.7 on 2024-11-25 16:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(max_length=50, unique=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('en attente', 'En Attente'), ('en parking', 'En Parking')], default='en attente', max_length=20)),
                ('image', models.ImageField(blank=True, null=True, upload_to='vehicule_images/')),
            ],
        ),
        migrations.AddField(
            model_name='course',
            name='vehicule',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='courses', to='api.vehicule'),
        ),
    ]
